version: '3'
services:
  # database:
  #   container_name: database
  #   image: postgis/postgis:13-master
  #   volumes:
  #     - ./data/database:/var/lib/postgresql/data
  #   networks:
  #     - directus
  #   environment:
  #     POSTGRES_USER: 'directus'
  #     POSTGRES_PASSWORD: 'directus'
  #     POSTGRES_DB: 'directus'

  # cache:
  #   container_name: cache
  #   image: redis:6
  #   networks:
  #     - ${NETWORK}

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - ${DIR_PORT}:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ${HOST_UPLOADS}:${STORAGE_LOCAL_UPLOADS}
      #- ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ${HOST_DATABASE}:${STORAGE_LOCAL_DATABASE}
      # If you want to load extensions from the host
      # - ${HOST_EXTENSIONS}:${STORAGE_LOCAL_EXTENSIONS}
    networks:
      - ${NETWORK}
    # depends_on:
    #   - cache
    #   - database
    env_file:
      - ./.env
    environment:

      LOG_LEVEL: ${LOG_LEVEL}

      KEY: ${DIR_KEY}
      SECRET: ${DIR_SECRET}

      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_STORE: ${CACHE_STORE}
      CACHE_REDIS: redis://cache:${REDIS_PORT}

      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      #STORAGE_LOCAL_PUBLIC_URL: ${STORAGE_LOCAL_PUBLIC_URL}
      STORAGE_LOCAL_DRIVER: ${STORAGE_LOCAL_DRIVER}
      STORAGE_LOCAL_ROOT: ${STORAGE_LOCAL_ROOT}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      
#      EMAIL_FROM: no-reply@directus.io #Email address from which emails are sent. Default: `no-reply@directus.io`
#      EMAIL_TRANSPORT: smtp  #What to use to send emails. One of `sendmail`, `smtp`. Based on the transport used, you must also provide the following configurations.
#      Sendmail (sendmail):
#      EMAIL_SENDMAIL_NEW_LINE: unix # — What new line style to use in sendmail. Default: unix
#      EMAIL_SENDMAIL_PATH: /usr/sbin/sendmail # — Path to your sendmail executable. Default: /usr/sbin/sendmail
#      SMTP (smtp)
#      EMAIL_SMTP_HOST: #— SMTP Host
#      EMAIL_SMTP_PORT: #— SMTP Port
#      EMAIL_SMTP_USER: #— SMTP User
#      EMAIL_SMTP_PASSWORD: #— SMTP Password
#      EMAIL_SMTP_POOL: #— Use SMTP pooling
#      EMAIL_SMTP_SECURE: #— Enable TLS

      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
